In [90]:
import numpy as np

In [115]:
#создаем матрицу оценок фильмов
X=np.zeros((6, 7))
X = np.array([[4,4,5,0,0,0,0], [5,5,3,4,3,0,0], [0,0,0,4,4,0,0], [0,0,0,5,4,5,3], [0,0,0,0,0,5,5], [0,0,0,0,0,4,4]])

In [92]:
#находим сингулярное разложение
U, s, V = numpy.linalg.svd(X, full_matrices=True)

In [93]:
U


array([[  3.12588157e-01,   4.88299765e-01,  -4.97486928e-01,
         -6.42399264e-01,  -6.06788790e-02,  -8.21965453e-17],
       [  5.81592898e-01,   5.04410043e-01,   3.39133215e-02,
          6.34303396e-01,   6.18813194e-02,   8.51855106e-17],
       [  2.91075769e-01,   7.31204099e-03,   5.79298849e-01,
         -2.32962739e-01,  -7.24819038e-01,  -5.55172221e-17],
       [  5.77180773e-01,  -3.75701377e-01,   3.15581314e-01,
         -3.03696910e-01,   5.77829951e-01,  -3.37590837e-17],
       [  2.98548926e-01,  -4.72363581e-01,  -4.39080193e-01,
          1.53175607e-01,  -2.85031755e-01,  -6.24695048e-01],
       [  2.38839141e-01,  -3.77890864e-01,  -3.51264154e-01,
          1.22540486e-01,  -2.28025404e-01,   7.80868809e-01]])

In [94]:
#вектор весов факторов
s

array([  1.26226575e+01,   1.06683922e+01,   7.29730704e+00,
         1.64107896e+00,   9.53988881e-01,   3.30004874e-17])

In [95]:
V

array([[ 0.32943278,  0.32943278,  0.2620462 ,  0.50516926,  0.41336817,
         0.42257386,  0.33112231],
       [ 0.41948676,  0.41948676,  0.37069587,  0.01578321,  0.00371872,
        -0.5391523 , -0.46871969],
       [-0.2494593 , -0.2494593 , -0.32692809,  0.55236202,  0.50446837,
        -0.27716403, -0.36365657],
       [ 0.36678304,  0.36678304, -0.79769844,  0.05293961, -0.14851717,
        -0.15992196,  0.21019662],
       [ 0.06990761,  0.06990761, -0.12342957,  0.24884869, -0.42171601,
         0.57850712, -0.63289054],
       [-0.71329073,  0.69789665,  0.01231527,  0.04002461, -0.04002461,
        -0.02001231,  0.02001231],
       [-0.07123497, -0.16370203,  0.1879496 ,  0.6108362 , -0.6108362 ,
        -0.3054181 ,  0.3054181 ]])

In [96]:
#превращаем вектор весов матрицу весов
S = np.zeros((6, 7))

In [97]:
S[:6,:6]=np.diag(s)
S

array([[  1.26226575e+01,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   1.06683922e+01,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   7.29730704e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.64107896e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   9.53988881e-01,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   3.30004874e-17,
          0.00000000e+00]])

In [98]:
#пробуем восстанавливать исходную матрицу
np.dot(U, np.dot(S, V))

array([[  4.00000000e+00,   4.00000000e+00,   5.00000000e+00,
          8.90520809e-16,   8.61392906e-16,   4.96822468e-16,
          5.95694946e-16],
       [  5.00000000e+00,   5.00000000e+00,   3.00000000e+00,
          4.00000000e+00,   3.00000000e+00,  -6.09094324e-16,
         -2.84405778e-16],
       [  4.33548827e-16,   1.40717458e-16,   5.00861171e-16,
          4.00000000e+00,   4.00000000e+00,  -1.87363603e-15,
         -1.32959913e-15],
       [  1.44657843e-15,   1.02592436e-15,   2.17384667e-15,
          5.00000000e+00,   4.00000000e+00,   5.00000000e+00,
          3.00000000e+00],
       [  8.88178420e-16,   4.44089210e-16,   4.44089210e-16,
         -1.08246745e-15,  -1.45716772e-15,   5.00000000e+00,
          5.00000000e+00],
       [  6.66133815e-16,   2.22044605e-16,   6.66133815e-16,
         -8.53483950e-16,  -7.91033905e-16,   4.00000000e+00,
          4.00000000e+00]])

In [99]:
Y=np.dot(U, np.dot(S, V))

In [100]:
#вычисляем ошибку приближения со всеми факторами
np.linalg.norm(X-Y)

1.3236908514815919e-14

In [101]:
#обнуляем 5-ый фактор
S[4,4]=0

In [102]:
Y=np.dot(U, np.dot(S, V))

In [103]:
np.linalg.norm(X-Y)

0.95398888134339621

In [104]:
#обнуляем 4-ый фактор
S[3,3]=0
Y=np.dot(U, np.dot(S, V))
np.linalg.norm(X-Y)

1.8982188885974189

In [105]:
from sklearn.decomposition import NMF


In [146]:
#инициализируем праметры неотрицательной матричной факторизации с тремя факторами
model = NMF(n_components=3, init='random', random_state=0)


In [147]:
#применяем модель к матрице оценок фильмов
model.fit(X) 


NMF(alpha=0.0, beta=1, eta=0.1, init='random', l1_ratio=0.0, max_iter=200,
  n_components=4, nls_max_iter=2000, random_state=0, shuffle=False,
  solver='cd', sparseness=None, tol=0.0001, verbose=0)

In [148]:
#извлекаем компоненты 
W = model.fit_transform(X);
H = model.components_;

In [149]:
#зрители-факторы
W


array([[  2.50491604e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  2.41547669e+00,   0.00000000e+00,   5.73219345e-07,
          1.93614354e+00],
       [  0.00000000e+00,   9.35309958e-03,   0.00000000e+00,
          2.20411318e+00],
       [  0.00000000e+00,   2.24595306e+00,   3.72392586e-01,
          6.48848113e-01],
       [  0.00000000e+00,   0.00000000e+00,   3.12835991e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   2.50268793e+00,
          0.00000000e+00]])

In [150]:
#факторы-зрители
H

array([[  1.76358424e+00,   1.76358424e+00,   1.63273555e+00,
          7.08820091e-02,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.68209007e+00,   1.29125765e+00,   1.96118758e+00,
          1.07071259e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.59311691e-05,   0.00000000e+00,   1.59828334e+00,
          1.59828253e+00],
       [  1.58726496e-01,   1.58726496e-01,   0.00000000e+00,
          1.88172836e+00,   1.69609196e+00,   0.00000000e+00,
          0.00000000e+00]])

In [151]:
#восстанавливаем исходную матрицу
Y=np.dot(W,H)
Y

array([[  4.41763045e+00,   4.41763045e+00,   4.08986547e+00,
          1.77553482e-01,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  4.56721389e+00,   4.56721389e+00,   3.94383465e+00,
          3.81451006e+00,   3.28387749e+00,   9.16166928e-07,
          9.16166467e-07],
       [  3.49851161e-01,   3.49851161e-01,   0.00000000e+00,
          4.16327504e+00,   3.75045590e+00,   1.83431827e-02,
          1.00144815e-02],
       [  1.02989387e-01,   1.02989387e-01,   0.00000000e+00,
          4.99885719e+00,   4.00061013e+00,   4.99992412e+00,
          2.99995880e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.98384306e-05,   0.00000000e+00,   5.00000551e+00,
          5.00000299e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.98707445e-05,   0.00000000e+00,   4.00000441e+00,
          4.00000239e+00]])

In [152]:
#находим суммарную ошибку
np.linalg.norm(X-Y)

1.7159544482539668

In [153]:
X-Y

array([[ -4.17630451e-01,  -4.17630451e-01,   9.10134534e-01,
         -1.77553482e-01,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  4.32786107e-01,   4.32786107e-01,  -9.43834651e-01,
          1.85489943e-01,  -2.83877488e-01,  -9.16166928e-07,
         -9.16166467e-07],
       [ -3.49851161e-01,  -3.49851161e-01,   0.00000000e+00,
         -1.63275040e-01,   2.49544104e-01,  -1.83431827e-02,
         -1.00144815e-02],
       [ -1.02989387e-01,  -1.02989387e-01,   0.00000000e+00,
          1.14281347e-03,  -6.10132784e-04,   7.58800160e-05,
          4.12016364e-05],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         -4.98384306e-05,   0.00000000e+00,  -5.50766951e-06,
         -2.99057651e-06],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
         -3.98707445e-05,   0.00000000e+00,  -4.40613561e-06,
         -2.39246121e-06]])

In [140]:
# на точность приближения влияют параметры модели (например, можно увеличить число факторов)